# Generated by Django 3.0.2 on 2020-02-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(help_text='Inglese la sucursal', max_length=50, unique=True, verbose_name='Nombre Sucursal:')),
                ('direccion', models.CharField(help_text='Inglese dirección sucursal', max_length=150, unique=True, verbose_name='Direción Sucursal:')),
                ('mapa', models.CharField(help_text='Ingrese el Mapa de la sucursal', max_length=100, unique=True, verbose_name='Link Google:')),
                ('telefono', models.CharField(help_text='Inglese telefono', max_length=20, unique=True, verbose_name='Telefono:')),
                ('on_off', models.BooleanField(default=True, help_text='Inglese el estado de la sucursal', verbose_name='Sucursal Activa:')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['sucursal'],
            },
        ),
    ]
