# Generated by Django 3.0.2 on 2020-02-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(help_text='Inglese el nombre de la Categoria', max_length=50, unique=True, verbose_name='Categoria:')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre_categoria'],
            },
        ),
    ]
