# Generated by Django 3.0.2 on 2020-02-17 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Inglese el Nombre del producto', max_length=50, unique=True, verbose_name='Nombre:')),
                ('descripcion', models.TextField(blank=True, help_text='Ingrese la Descripción del prodcuto', max_length=100, verbose_name='Descripcion:')),
                ('imagen', models.FileField(help_text='Ingrese la imagen del prodcuto', upload_to='image_produc', verbose_name='Imagen Producto:')),
                ('id_categoria', models.ForeignKey(help_text='Ingrese la categoria del producto', on_delete=django.db.models.deletion.CASCADE, to='supermercado.Categoria', verbose_name='Categoria Producto:')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
