# Generated by Django 3.0.2 on 2020-02-17 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
                ('precio', models.IntegerField(help_text='Inglese el precio del producto en $', verbose_name='Precio:')),
                ('id_producto', models.ForeignKey(help_text='Ingrese el nombre del producto', on_delete=django.db.models.deletion.CASCADE, to='supermercado.Producto', verbose_name='Producto:')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
    ]
