# Generated by Django 3.0.2 on 2020-02-17 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supermercado', '0005_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(help_text='Ingrese la fecha de nacimiento', verbose_name='Fecha Nacimiento:')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indefinido')], default='I', help_text='Ingrese su sexo', max_length=1, verbose_name='Sexo:')),
                ('cedula', models.CharField(blank=True, help_text='Ingrese su numero de cedula', max_length=20, unique=True, verbose_name='Cedula:')),
                ('telefono', models.CharField(help_text='Inglese telefono', max_length=20, unique=True, verbose_name='Telefono:')),
                ('id_usuario', models.ForeignKey(help_text='Ingrese el usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario:')),
            ],
            options={
                'verbose_name': 'Detalles Usuario',
                'verbose_name_plural': 'Detalles Usuarios',
            },
        ),
    ]
