# Generated by Django 3.0.2 on 2020-02-17 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supermercado', '0006_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, help_text='Inglese la cantidad de productos', verbose_name='Cantidad:')),
                ('on_off', models.BooleanField(default=True, help_text='Inglese el estado del producto en el carrito', verbose_name='Producto Activo:')),
                ('id_inventario', models.ForeignKey(help_text='Ingrese inventario que decea agregar al carrito', on_delete=django.db.models.deletion.CASCADE, to='supermercado.Inventario', verbose_name='Inventario:')),
                ('id_usuario', models.ForeignKey(help_text='Ingrese el usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario:')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'unique_together': {('id_usuario', 'id_inventario')},
            },
        ),
    ]
